from enum import Enum


class ErrosLexicos(Enum):
  CARACTERE_INVALIDO = 1
  LEXEMA_MAL_FORMADO = 2
  LEXEMA_MAL_FORMADO_REAL = 3
  LEXEMA_MAL_FORMADO_EXP = 4
  LEXEMA_MAL_FORMADO_EXP_SINAL = 5
  LITERAL_INCOMPLETA = 6
  COMENTARIO_INCOMPLETO = 7
